const countryNames = [
    { countryName: 'Unite States Dollar', code: 'USD' },
    { countryName: 'Japanese Yen', code: 'JPY' },
    { countryName: 'Bulgarian Lev', code: 'BGN' },
    { countryName: 'Czech Koruna', code: 'CZK' },
    { countryName: 'Danish krone', code: 'DKK' },
    { countryName: 'Pound Sterlin', code: 'GBP' },
    { countryName: 'Hungary Forint', code: 'HUF' },
    { countryName: 'Polish złoty', code: 'PLN' },
    { countryName: 'Romania Leu', code: 'RON' },
    { countryName: 'Sweden Krona', code: 'SEK' },
    { countryName: 'Swiss Franc', code: 'CHF' },
    { countryName: 'Iceland Krona', code: 'ISK' },
    { countryName: 'Norway Krona', code: 'NOK' },
    { countryName: 'Croatia Kuna', code: 'HRK' },
    { countryName: 'Russian Ruble', code: 'RUB' },
    { countryName: 'Turkey Lira', code: 'TRY' },
    { countryName: 'Austrialian Dollar', code: 'AUD' },
    { countryName: 'Brazil Real', code: 'BRL' },
    { countryName: 'Canada Dollar', code: 'CAD' },
    { countryName: 'Chinese Renminbi', code: 'CNY' },
    { countryName: 'Hong Kong Dollar', code: 'HKD' },
    { countryName: 'Indonesia Rupiah', code: 'IDR' },
    { countryName: 'Israeli New Shekel', code: 'ILS' },
    { countryName: 'India Rupee', code: 'INR' },
    { countryName: 'South Korea Won', code: 'KRW' },
    { countryName: 'Mexican Peso', code: 'MXN' },
    { countryName: 'Malaysia Ringgit', code: 'MYR' },
    { countryName: 'New Zeland Dollar', code: 'NZD' },
    { countryName: 'Philippine Peso', code: 'PHP' },
    { countryName: 'Singaporem Dollar', code: 'SGD' },
    { countryName: 'Thai Baht', code: 'THB' },
    { countryName: 'South Africa Rand', code: 'ZAR' },
];

export default countryNames;
