const countryNames = [
    { countryName: 'Unite States Dollar', code: 'USD' },
    { countryName: 'Japanese Yen', code: 'JPY' },
    { countryName: 'Bulgarian Lev', code: 'BGN' },
    { countryName: 'Czech Koruna', code: 'CZK' },
    { countryName: 'Danish krone', code: 'DKK' },
    { countryName: 'Pound Sterlin', code: 'GBP' },
    { countryName: 'Hungary Forint', code: 'HUF' },
    { countryName: 'Polish złoty', code: 'PLN' },
    { countryName: 'Romania Leu', code: 'RON' },
    { countryName: 'Sweden Krona', code: 'SEK' },
    { countryName: 'Swiss Franc', code: 'CHF' },
    { countryName: 'Iceland Krona', code: 'ISK' },
    { countryName: 'Norway Krona', code: 'NOK' },
    { countryName: 'Croatia Kuna', code: 'HRK' },
    { countryName: 'Russian Ruble', code: 'RUB' },
    { countryName: 'Turkey Lira', code: 'TRY' },
    { countryName: 'Austrialian Dollar', code: 'AUD' },
    { countryName: 'Brazil Real', code: 'BRL' },
    { countryName: 'Canada Dollar', code: 'CAD' },
    { countryName: 'Chinese Renminbi', code: 'CNY' },
    { countryName: 'Hong Kong Dollar', code: 'HKD' },
    { countryName: 'Indonesia Rupiah', code: 'IDR' },
    { countryName: 'Israeli New Shekel', code: 'ILS' },
    { countryName: 'India Rupee', code: 'INR' },
    { countryName: 'South Korea Won', code: 'KRW' },
    { countryName: 'Mexican Peso', code: 'MXN' },
    { countryName: 'Malaysia Ringgit', code: 'MYR' },
    { countryName: 'New Zeland Dollar', code: 'NZD' },
    { countryName: 'Philippine Peso', code: 'PHP' },
    { countryName: 'Singaporem Dollar', code: 'SGD' },
    { countryName: 'Thai Baht', code: 'THB' },
    { countryName: 'South Africa Rand', code: 'ZAR' },
];

const data = [
    { currency: "USD", rate: 1.1417 },
    { currency: "JPY", rate: 128.89 },
    { currency: "BGN", rate: 1.9558 },
    { currency: "CZK", rate: 25.782 },
    { currency: "DKK", rate: 7.4603 },
    { currency: "GBP", rate: 0.87870 },
    { currency: "HUF", rate: 321.62 },
    { currency: "PLN", rate: 4.3202 },
    { currency: "RON", rate: 4.6612 },
    { currency: "SEK", rate: 10.3123 },
    { currency: "CHF", rate: 1.1422 },
    { currency: "ISK", rate: 138.10 },
    { currency: "NOK", rate: 9.5143 },
    { currency: "HRK", rate: 7.4393 },
    { currency: "RUB", rate: 75.3127 },
    { currency: "TRY", rate: 6.2539 },
    { currency: "AUD", rate: 1.5840 },
    { currency: "BRL", rate: 4.2205 },
    { currency: "CAD", rate: 1.4956 },
    { currency: "CNY", rate: 7.8712 },
    { currency: "HKD", rate: 8.9391 },
    { currency: "IDR", rate: 17031.88 },
    { currency: "ILS", rate: 4.2160 },
    { currency: "INR", rate: 82.7085 },
    { currency: "KRW", rate: 1276.25 },
    { currency: "MXN", rate: 22.8399 },
    { currency: "MYR", rate: 4.7483 },
    { currency: "NZD", rate: 1.7154 },
    { currency: "PHP", rate: 60.693 },
    { currency: "SGD", rate: 1.5686 },
    { currency: "THB", rate: 37.539 },
    { currency: "ZAR", rate: 16.3720 },
];

export {
    data,
    countryNames
}